[build]
  base = "Frontend/"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://codeatlas1.onrender.com"
  REACT_APP_GUN_URL = "https://codeatlas-gunjs.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://codeatlas1.onrender.com"
  REACT_APP_GUN_URL = "https://codeatlas-gunjs.onrender.com"
